import type { Metadata } from "next";
import { Manrope, Raleway } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-manrope",
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${raleway.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
